'use client'

import { ScanLine, ShieldCheck, ArrowRight, LockKeyhole, UserPlus } from 'lucide-react'

function AuthShell({ signup = false }: { signup?: boolean }) {
  return <main className="auth-page"><section className="auth-visual"><div className="auth-grid" /><div className="auth-brand"><ScanLine size={22} /> Niyam<span>AI</span></div><div className="auth-copy"><div className="eyebrow"><span className="pulse" /> ENFORCEMENT INTELLIGENCE</div><h1>Evidence-driven<br /><span>compliance.</span></h1><p>Transforming field inspection from manual verification into intelligent, auditable enforcement.</p></div><div className="auth-scan"><div className="auth-package"><b>XYZ</b><small>PREMIUM BISCUITS<br />500 g</small></div><i>MRP • 98%</i><i>NET QTY • 96%</i></div></section><section className="auth-panel"><div className="auth-card"><div className="eyebrow">AUTHORIZED ACCESS</div><h2>{signup ? 'Create officer account' : 'Welcome back, Officer.'}</h2><p>{signup ? 'Set up your secure enforcement workspace.' : 'Sign in to your enforcement intelligence workspace.'}</p>{signup && <label>Full name<input placeholder="Arjun Sen" /></label>}<label>Official email / Officer ID<input type="email" placeholder="officer@niyam.ai" /></label><label>Password<input type="password" placeholder="Enter secure password" /></label>{signup && <label>Confirm password<input type="password" placeholder="Repeat password" /></label>} {!signup && <div className="auth-options"><label className="check-label"><input type="checkbox" /> Remember me</label><a href="#">Forgot password?</a></div>}<a className="button primary auth-submit" href={signup ? '/onboarding' : '/onboarding'}>{signup ? <UserPlus size={16} /> : <LockKeyhole size={16} />}{signup ? 'Create account' : 'Sign in'}<ArrowRight size={16} /></a><div className="auth-divider"><span>or</span></div><p className="auth-switch">{signup ? 'Already registered?' : 'New enforcement officer?'} <a href={signup ? '/login' : '/signup'}>{signup ? 'Sign in' : 'Create account'}</a></p><div className="auth-status"><ShieldCheck size={15} /><span><b>SYSTEM STATUS</b>All services operational</span><i /></div></div></section></main>
}

export function LoginPage() { return <AuthShell /> }
export function SignupPage() { return <AuthShell signup /> }

export function OnboardingPage() { return <main className="onboarding-page"><div className="onboarding-card"><div className="auth-brand"><ScanLine size={22} /> Niyam<span>AI</span></div><div className="eyebrow">OFFICER WORKSPACE / FIRST SESSION</div><h1>Welcome back, Officer.</h1><p>Your enforcement intelligence workspace is ready.</p><div className="role-card"><div className="role-icon"><ShieldCheck size={22} /></div><div><div className="eyebrow">FIELD ENFORCEMENT OFFICER</div><h2>Arjun Sen</h2><p>Kolkata, West Bengal • WB-LM-042</p></div><span className="badge badge-green">ACTIVE</span></div><div className="access-list"><span>Field inspections</span><span>AI scanner</span><span>Evidence capture</span><span>Compliance reports</span></div><a className="button primary" href="/dashboard">Enter command center <ArrowRight size={16} /></a></div></main> }

export { AuthShell }
